services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./drizzle:/app/drizzle
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./biome.json:/app/biome.json
      - /app/node_modules
